Agregar scripts de hooks al repo

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,6 +1,6 @@
-#!/ bin/ bash
+#!/bin/bash
 echo "Ejecutando pruebas antes del push..."
 if ! make test; then
-	echo "Las ␣ pruebas ␣ fallaron .␣ Push ␣ abortado ."
-	exit 1
+    echo "Las pruebas fallaron. Abortando push."
+    exit 1
 fi
